website/models.py
from . import db
from flask_login import UserMixin

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(1000), nullable= False)
    description = db.Column(db.Text, nullable=False)
    price = db.Column(db.Float, nullable=False)
    image_url = db.Column(db.String(20000))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    fullname = db.Column(db.String(150))

class CartItem(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    product_id = db.Column(db.Integer, db.ForeignKey('product.id'), nullable=False)
    quantity = db.Column(db.Integer, nullable=False)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app=Flask(__name__)
    app.config['SECRET_KEY'] = 'my-secret-key'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from . import models

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return models.User.query.get(int(id))


    return app

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, Product
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Login successful", category="success")
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash("Incorrect password, Please Try Again!", category="error")
        else:
            flash("Email does not exist", category="error")
    data = request.form
    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/register', methods=['GET','POST'])
def register():
    if request.method == 'POST':
        email = request.form.get('email')
        fullname = request.form.get('fullname')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email already exists", category="error")
        elif len(email) <6:
            flash("Enter a valid email address", category="error")
        elif len(fullname) <3:
            flash("Enter a valid name", category="error")
        elif password1 != password2:
            flash("Passwords do not match", category="error")
        elif len(password1)<7:
            flash("Password must be at least 7 characters", category="error")
        else:
            # add user to database
            new_user  = User(email = email, fullname = fullname, password = generate_password_hash(password1, method="sha256"))
            db.session.add(new_user)
            db.session.commit()

            flash("Account created", category="success")
            return redirect(url_for('views.home'))
    return render_template("register.html",user=current_user)

website/views.py
from flask import Blueprint, render_template, session, redirect, url_for, flash, request
from flask_login import login_user, login_required, logout_user, current_user
from . import models, db
from .models import Product, User, CartItem
from collections import defaultdict

views = Blueprint('views', __name__)

@views.route('/')
def home():
    products = Product.query.all()
    return render_template("home.html",products=products, user=current_user)

@views.route('/product/<int:product_id>')
def product_detail(product_id):
    product = Product.query.get(product_id)
    return render_template("product_detail.html",product=product, user=current_user)

@views.route('/shopping_cart/<int:product_id>')
def shopping_cart(product_id):
    if not current_user.is_authenticated:
        return redirect(url_for("auth.login"))

    user_id = session['_user_id']
    user = User.query.get(user_id)
    product = Product.query.get(product_id)

    if user and product:
        cart_item = CartItem.query.filter_by(user_id=user_id, product_id=product_id).first()
        
        if cart_item:
            cart_item.quantity+=1
        else:
            cart_item=CartItem(user_id=user_id, product_id=product_id, quantity=1)
            db.session.add(cart_item)
    
        db.session.commit()
        flash(f'{product.name} has been added to cart successfully!', 'success')
    else:
        flash(f'Error adding product to cart', 'danger')
    return redirect(request.referrer)

@views.route('/mycart', methods=['GET', 'POST'])
def mycart():
    if not current_user.is_authenticated:
        flash('Please login to view your cart', 'warning')
        return redirect(url_for("auth.login"))
    
    user_id = session['_user_id']
    user = User.query.get(user_id)
    cart_item = CartItem.query.filter_by(user_id=user_id).all()
    total=0
    product_dict=defaultdict(Product)
    for item in cart_item:
        product = Product.query.get(item.product_id)
        product_dict[item]=product
        total += product.price*item.quantity

    if request.method == 'POST':
        card_number = request.form['card_number']
        card_expiry = request.form['card_expiry']
        card_cvv = request.form['card_cvv']
        print('--------------------')

        if card_number == '1234567890123456' and card_expiry == '12/30' and card_cvv == '123':
            flash('Card information is invalid. Please try again', 'error')
        else:
            for item in cart_item:
                db.session.delete(item)

            db.session.commit()
            flash('Payment Successful. Thank you for your order!', 'success')
            return redirect(url_for('views.home'))

    return render_template('mycart.html', product_dict=product_dict, total=total, user=current_user)


@views.route('/remove_from_cart/<int:item_id>')
def remove_from_cart(item_id):
    if current_user.is_authenticated():
        cart_item = CartItem.query.get(item_id=item_id)
        if cart_item:
            db.session.delete(cart_item)
            db.session.commit()
            flash('Item removed from cart.', 'success')
        else:
            flash('Item not found.', 'danger')
    return redirect(url_for('views.mycart'))


@views.route('/remove_one_from_cart/<int:item_id>')
def remove_one_from_cart(item_id):
    if current_user.is_authenticated:
        user_id = session['_user_id']
        cart_item = CartItem.query.filter_by(id=item_id, user_id=user_id).first()

        if cart_item:
            if cart_item.quantity > 1:
                cart_item.quantity -=1
                db.session.commit()
            else:
                db.session.delete(cart_item)
                db.session.commit()
                flash('Item removed from cart.', 'success')
        else:
            flash('Item not found in cart.', 'danger')
    
    return redirect(url_for('views.mycart'))

@views.route('/checkout')
def checkout():
    user_id = session['_user_id']
    user = User.query.get(user_id)
    cart_item = CartItem.query.filter_by(user_id=user_id).all()
    total=0
    product_dict=defaultdict(Product)
    for item in cart_item:
        product = Product.query.get(item.product_id)
        product_dict[item]=product
        total += product.price*item.quantity
    
    
    return render_template('checkout.html', total=total, user=current_user)

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          <a class="nav-item nav-link" id="cart" href="/mycart">My Cart</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}          
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}
  </body>
</html>

website/templates/checkout.html
{% extends "base.html" %}{% block title %}Shop It Here{% endblock %}
{% block content %}
<h1>Order Placed!!</h1>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}{% block title %}Shop It Here{% endblock %}
{% block content %}
<section style="background-color: #eee;">
  <div class="container py-5">
    {% for product in products %}
    <div class="row justify-content-center mb-3">
      <div class="col-md-12 col-xl-10">
        <div class="card shadow-0 border rounded-3">
          <div class="card-body">
            <div class="row">
              <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0">
                <div class="bg-image hover-zoom ripple rounded ripple-surface">
                  <img src={{ product.image_url}}
                    class="w-100" />
                  <a href="#!">
                    <div class="hover-overlay">
                      <div class="mask" style="background-color: rgba(253, 253, 253, 0.15);"></div>
                    </div>
                  </a>
                </div>
              </div>
              <div class="col-md-6 col-lg-6 col-xl-6">
                <h5>{{ product.name }}</h5>
                <div class="d-flex flex-row">
                  <div class="text-danger mb-1 me-2">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                  </div>
                  <span>310</span>
                </div>
                <div class="mt-1 mb-0 text-muted small">
                  <span>100% cotton</span>
                  <span class="text-primary"> • </span>
                  <span>Light weight</span>
                  <span class="text-primary"> • </span>
                  <span>Best finish<br /></span>
                </div>
                <div class="mb-2 text-muted small">
                  <span>Unique design</span>
                  <span class="text-primary"> • </span>
                  <span>For men</span>
                  <span class="text-primary"> • </span>
                  <span>Casual<br /></span>
                </div>
                <p class="text-truncate mb-4 mb-md-0">
                    {{ product.description }}
                </p>
              </div>
              <div class="col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start">
                <div class="d-flex flex-row align-items-center mb-1">
                  <h4 class="mb-1 me-1">${{ product.price }}</h4>
                  <span class="text-danger"><s>${{ product.price + 50 }}</s></span>
                </div>
                <h6 class="text-success">Free shipping</h6>
                <div class="d-flex flex-column mt-4">
                  <a href="{{ url_for('views.product_detail',product_id=product.id) }}" class="btn btn-primary btn-sm" type="button">Details</a>
                  <a href="{{ url_for('views.shopping_cart',product_id=product.id) }}" class="btn btn-outline-primary btn-sm mt-2" type="button">
                    Add to cart
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}{% block title %}Login{% endblock %}
{% block content %}
<form method = "POST">
    <h3 align = "center">Login</h3>
    <div class = "form-group">
        <label for="email">Email Address</label>
        <input type = "email" class = "form-control" id = "email" name = "email" placeholder = "Enter email" />
    </div>
   
    <div class = "form-group">
        <label for="password">Password</label>
        <input type = "password" class = "form-control" id = "password" name = "password" placeholder = "Enter Password" />
    </div>
    
    <br />
    <button type="submit" class="btn btn-primary">Submit </button>
</form>
{% endblock %}

website/templates/mycart.html
{% extends "base.html" %}{% block title %}Shop It Here{% endblock %}
{% block content %}
<form method = "POST">
  <section class="h-100 h-custom">
    <div class="container h-100 py-5">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" class="h5">Shopping Bag</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Price</th>
                </tr>
              </thead>
              <tbody>
                {% for item, product in product_dict.items() %}
                <tr>
                  <th scope="row">
                    <div class="d-flex align-items-center">
                      <img src={{ product.image_url}} class="rounded" alt="Cinque Terre" width="254" height="136">
                      <div class="flex-column md-4">
                        <p class="mb-2" style="margin-left: 25px;">{{ product.name}}</p>
                        <p class="mb-0" style="margin-left: 25px;">{{ product.description}}</p>
                      </div>
                    </div>
                  </th>
                  <td class="align-middle" >
                    <div class="d-flex flex-row" >
                      <a href="{{ url_for('views.remove_one_from_cart',item_id=item.id) }}" class="text-decoration-none"
                        onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                        <i style="padding-right: 10px"><b>-</b></i>
                      </a>

                      <input id="form1" min="0" name="quantity" value={{ item.quantity}} type="number"
                        class="form-control form-control-sm" style="width: 50px;" />

                      <a href="{{ url_for('views.shopping_cart',product_id=product.id) }}" class="text-decoration-none"
                        onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                        <i style="padding-left: 10px"><b>+</b></i>
                      </a>
                    </div>
                  </td>
                  <td class="align-middle">
                    <p class="mb-0" style="font-weight: 500;">${{product.price}}</p>
                  </td>
                </tr>
                {% endfor %}

              </tbody>
            </table>
          </div>

          <div class="card shadow-2-strong mb-5 mb-lg-0" style="border-radius: 16px;">
            <div class="card-body p-4">

              <div class="row">
                <div class="col-md-6 col-lg-4 col-xl-3 mb-4 mb-md-0">
                    <div class="d-flex flex-row pb-3">
                      <div class="d-flex align-items-center pe-2">
                        <input class="form-check-input" type="radio" name="radioNoLabel" id="radioNoLabel1v"
                          value="" aria-label="..." checked />
                      </div>
                      <div class="rounded border w-100 p-3">
                        <p class="d-flex align-items-center mb-0">
                          <i class="fa fa-cc-mastercard fa-2x"style="padding-right: 10px"></i>Credit
                          Card
                        </p>
                      </div>
                    </div>
                    <div class="d-flex flex-row pb-3">
                      <div class="d-flex align-items-center pe-2">
                        <input class="form-check-input" type="radio" name="radioNoLabel" id="radioNoLabel2v"
                          value="" aria-label="..." />
                      </div>
                      <div class="rounded border w-100 p-3">
                        <p class="d-flex align-items-center mb-0">
                          <i class="fa fa-cc-visa fa-2x" style="padding-right: 10px" ></i>Debit Card
                        </p>
                      </div>
                    </div>
                    <div class="d-flex flex-row">
                      <div class="d-flex align-items-center pe-2">
                        <input class="form-check-input" type="radio" name="radioNoLabel" id="radioNoLabel3v"
                          value="" aria-label="..." />
                      </div>
                      <div class="rounded border w-100 p-3">
                        <p class="d-flex align-items-center mb-0">
                          <i class="fa fa-cc-paypal fa-2x" style="padding-right: 10px"></i>PayPal
                        </p>
                      </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4 col-xl-6">
                  <div class="row">
                    <div class="col-12 col-xl-6">
                      <div class="form-outline mb-4 mb-xl-5" >
                        <label for="card-holder">Card Holder</label>
                        <input id="card-holder" type="text" class="form-control" placeholder="Card Holder" aria-label="Card Holder" aria-describedby="basic-addon1">
                      </div>
                      <div class="form-outline mb-4 mb-xl-5">
                        <label for="card_expiry">Expiration Date</label>
                        <input type="text" name="card_expiry" class="form-control" placeholder="MM/YY" aria-label="MM" aria-describedby="basic-addon1"
                        size="7" id="exp" minlength="5" maxlength="5" required>
                      </div>
                    </div>
                    <div class="col-12 col-xl-6">
                      <div class="form-outline mb-4 mb-xl-5">
                        <label for="card_number">Card Number</label>
                        <input id="card_number" name="card_number" type="text" class="form-control" placeholder="1111 2222 3333 4444" 
                        aria-label="Card Holder" aria-describedby="basic-addon1"  minlength="15" maxlength="19" required >
                      </div>

                      <div class="form-outline mb-4 mb-xl-5">
                        <label for="card_cvv">CVV</label>
                        <input id="card_cvv" name="card_cvv" type="password" class="form-control" placeholder="&#9679;&#9679;&#9679;"
                        aria-label="Card Holder" aria-describedby="basic-addon1" size="1" minlength="3" maxlength="3" required>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 col-xl-3">
                  <div class="d-flex justify-content-between" style="font-weight: 500;">
                    <p class="mb-2">Subtotal</p>
                    <p class="mb-2">${{total}}</p>
                  </div>

                  <div class="d-flex justify-content-between" style="font-weight: 500;">
                    <p class="mb-0">Shipping</p>
                    <p class="mb-0">$2.99</p>
                  </div>

                  <hr class="my-4">

                  <div class="d-flex justify-content-between mb-4" style="font-weight: 500;">
                    <p class="mb-2">Total (tax included)</p>
                    <p class="mb-2">${{total+2.99}}</p>
                  </div>

                  <button type="submit" class="btn btn-primary btn-block btn-lg">
                    <div class="d-flex justify-content-between">
                      <span>Checkout</span>
                      <span>${{total+2.99}}</span>
                    </div>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</form>
{% endblock %}

website/templates/product_detail.html
{% extends "base.html" %}{% block title %}Viewing Product{% endblock %}
{% block content %}
<section style="background-color: #eee;">
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6 col-xl-4">
          <div class="card" style="border-radius: 15px;">
            <div class="bg-image hover-overlay ripple ripple-surface ripple-surface-light"
              data-mdb-ripple-color="light">
              <img src="{{ product.image_url }}"
                style="border-top-left-radius: 15px; border-top-right-radius: 15px;" class="img-fluid"
                alt="Laptop" />
              <a href="#!">
                <div class="mask"></div>
              </a>
            </div>
            <div class="card-body pb-0">
              <div class="d-flex justify-content-between">
                <div>
                  <p><a href="#!" class="text-dark">{{ product.name }}</a></p>
                  <p class="small text-muted">{{ product.description }}</p>
                </div>
                <div>
                  <div class="d-flex flex-row justify-content-end mt-1 mb-4 text-danger">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                  </div>
                  <p class="small text-muted">Rated 4.0/5</p>
                </div>
              </div>
            </div>
            <hr class="my-0" />
            <div class="card-body pb-0">
              <div class="d-flex justify-content-between">
                <p><a href="#!" class="text-dark">${{ product.price }}</a></p>
                <p class="text-dark">#### 8787</p>
              </div>
              <p class="small text-muted">VISA Platinum</p>
            </div>
            <hr class="my-0" />
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-center pb-2 mb-1">
                <a href="#!" class="text-dark fw-bold">Cancel</a>
                <a href="{{ url_for('views.shopping_cart',product_id=product.id) }}" type="button" class="btn btn-primary">Add to Cart</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

website/templates/register.html
{% extends "base.html" %}{% block title %}Register{% endblock %}
{% block content %}
<form method = "POST">
    <h3 align = "center">Register</h3>
    <div class = "form-group">
        <label for="email">Email Address</label>
        <input type = "email" class = "form-control" id = "email" name = "email" placeholder = "Enter email" />
    </div>
    <div class = "form-group">
        <label for="fullname">Full Name</label>
        <input type = "text" class = "form-control" id = "fullname" name = "fullname" placeholder = "Enter Full Name" />
    </div>
    <div class = "form-group">
        <label for="password1">Password</label>
        <input type = "password" class = "form-control" id = "password1" name = "password1" placeholder = "Enter Password" />
    </div>
    <div class = "form-group">
        <label for="password2">Password (Confirm)</label>
        <input type = "password" class = "form-control" id = "password2" name = "password2" placeholder = "Confirm Password" />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit </button>
</form>
{% endblock %}